[package]
name = "checker"
version = "0.1.0"
edition = "2021"

[dependencies]
syntax = { path = "../syntax" }
data = { path = "../data"}

indexmap = "2.1.0"

# CPU-bound async tasks
tokio = { version = "1.33.0", features = ["rt"] }

# Utility / Code Cleanliness
anyhow = "1.0.75"
async-trait = { path = "../../crates/async-trait" }
async-recursion = { path = "../../crates/async-recursion" }
