[package]
name = "checker"
version = "0.1.0"
edition = "2021"

[dependencies]
syntax = { path = "../syntax" }

indexmap = "1.9.3"

# CPU-bound async tasks
tokio = { version = "1.27.0", features = ["rt"] }

# Utility / Code Cleanliness
anyhow = "1.0.69"
async-trait = { version = "0.1.69", path = "../../crates/async-trait" }
async-recursion = { version = "1.0.5", path = "../../crates/async-recursion" }

# Debugging
no_deadlocks = "1.3.1"