[package]
name = "checker"
version = "0.1.0"
edition = "2021"

[dependencies]
syntax = { path = "../syntax" }
compilers = { path = "../compilers/compilers" }

# CPU-bound async tasks
tokio = { version = "1.27.0", features = ["rt"] }

# Utility / Code Cleanliness
anyhow = "1.0.69"