[package]
name = "compiler-llvm"
version = "0.1.0"
edition = "2021"

[dependencies]
syntax = { path = "../../syntax" }

async-trait = { version = "0.1.69", path = "../../../crates/async-trait" }

tokio = { version = "1.27.0", features = ["rt"] }

llvm-sys = "130.1.2"
inkwell = { version = "0.2.0", features = ["llvm13-0"] }

# Debugging
no_deadlocks = {version = "1.3.1", default-features = false}