[package]
name = "compiler-llvm"
version = "0.1.0"
edition = "2021"

[dependencies]
syntax = { path = "../../syntax" }

async-trait = { version = "0.1.69", path = "../../../crates/async-trait" }

tokio = { version = "1.27.0", features = ["rt"] }

llvm-sys = "130.0.0"
inkwell = { version = "0.1.1", features = ["llvm13-0"] }