[package]
name = "syntax"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
async-trait = "0.1.68"
lazy_static = "1.4.0"

tokio = { version = "1.27.0", features = [ "rt" ] }
async-recursion = { version = "1.0.5", path = "../../crates/async-recursion" }