[package]
name = "syntax"
version = "0.1.0"
edition = "2021"

[dependencies]
data = { version = "0.1.0", path = "../data" }
anyhow = "1.0.70"
async-trait = { version = "0.1.69", path = "../../crates/async-trait" }
lazy_static = "1.4.0"
indexmap = "1.9.3"

chalk-solve = "0.93.0"
chalk-ir = "0.93.0"
chalk-recursive = "0.93.0"

tokio = { version = "1.27.0", features = [ "rt" ] }
async-recursion = { version = "1.0.5", path = "../../crates/async-recursion" }

# Debugging
no_deadlocks = "1.3.1"