[package]
name = "syntax"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
async-trait = { version = "0.1.69", path = "../../crates/async-trait" }
lazy_static = "1.4.0"
indexmap = "1.9.3"

chalk-integration = { version = "0.93.0-dev.0", path = "../../crates/chalk/chalk-integration" }
chalk-solve = { version = "0.93.0-dev.0", path = "../../crates/chalk/chalk-solve" }
chalk-ir = { version = "0.93.0-dev.0", path = "../../crates/chalk/chalk-ir" }
chalk-recursive = { version = "0.93.0-dev.0", path = "../../crates/chalk/chalk-recursive" }

tokio = { version = "1.27.0", features = [ "rt" ] }
async-recursion = { version = "1.0.5", path = "../../crates/async-recursion" }

# Debugging
no_deadlocks = "1.3.0"