version = 1

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "nightly"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["nodejs"]