version = 1

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "nightly"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "18"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["nodejs"]