[workspace]
members = [
    "language/checker",
    "language/parser",
    "language/runner",
    "language/syntax",
    "language/data",

    "language/compilers/llvm",

    "tools/magpie",
    "tools/magpie/magpie-wrapper",
    "tools/ide-plugins/raven-language-server"
]
resolver = "2"