[workspace]
exclude = [
    "language/compilers",
    "tools/ide-plugins"
]
members = [
    "language/*",
    "language/compilers/*",

    "tools/*",
    "tools/magpie/magpie-wrapper",
]
resolver = "2"