[workspace]
members = [
    "language/checker",
    "language/cli",
    "language/parser",
    "language/runner",
    "language/syntax",

    "language/compilers/compilers",
    "language/compilers/llvm",
]