[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[dependencies]
syntax = { path = "../syntax" }

async-recursion = { version = "1.0.5", path = "../../crates/async-recursion" }
anyhow = "1.0.75"
indexmap = "2.1.0"

tokio = { version = "1.33.0", features = ["rt"] }