[package]
name = "compilers"
version = "0.1.0"
edition = "2021"

[dependencies]
syntax = { path = "../../syntax" }

# Util
anyhow = "1.0.70"
async-trait = { version = "0.1.69", path = "../../../crates/async-trait" }