[package]
name = "raven-intellij-natives"
version = "0.1.0"
edition = "2021"

[dependencies]
syntax = { path = "../../../language/syntax" }
parser = { path = "../../../language/parser" }

jni = "0.21.1"