[package]
name = "functions"
version = "0.1.0"
edition = "2021"

[dependencies]
program = { path = "../program" }
util = { path = "../util" }
types = { path = "../types" }
new-runner = { path = "../runner" }
new-parser = { path = "../parser" }
lexer = { path = "../lexer" }

indexmap = "2.1.0"