[package]
name = "new-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
lexer = { path = "../lexer" }
new-runner = { path = "../runner" }
program = { path = "../program" }
types = { path = "../types" }
util = { path = "../util" }

indexmap = "2.1.0"