[package]
name = "raven-language-server"
version = "0.1.0"
edition = "2021"

[dependencies]
syntax = { path = "../../../language/syntax" }
parser = { path = "../../../language/parser" }

crossbeam-channel = "0.5.8"
json = "0.12.4"