[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
parser = { path = "../parser" }
ast = { path = "../ast" }

llvm-sys = "130.0.0"
inkwell = { version = "0.1.1", features = [ "llvm13-0" ] }