[package]
name = "magpie"
version = "0.1.0"
edition = "2021"

[dependencies]
runner = { path = "../../language/runner" }
data = { path = "../../language/data" }

async-recursion = { path = "../../crates/async-recursion" }

include_dir = "0.7.3"

tokio = { version = "1.25.0", features = ["rt-multi-thread", "macros"] }