name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  llvm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: llvm/llvm-project
    - name: LLVM Deps
      run: sudo apt-get install cmake-data && sudo apt-get install cmake
    - name: LLVM
      run: ./llvm/utils/docker/build_docker_image.sh --source debian10 --docker-repository clang-debian10 --docker-tag "staging" -p clang -i install-clang -i install-clang-resource-headers -- -DCMAKE_BUILD_TYPE=Release
    
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Add Nightly
      run: rustup toolchain install nightly
    - name: Build
      run: cargo +nightly build --verbose
