name: Raven-Linux

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# Cancel any other build tasks running right now to prevent stale uploads
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  DEEPSOURCE_DSN: ${{secrets.DEEPSOURCE_DSN}}

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Add Nightly
      run: rustup toolchain install nightly
    - name: Test
      run: RUSTFLAGS="-C instrument-coverage" cargo +nightly test --verbose --bin magpie -- --nocapture
    - name: Build
      run: cargo +nightly build --verbose --release --bin magpie
    - name: Build Wrapper
      run: cargo +nightly build --verbose --release --bin magpie-wrapper
    - name: Release Raven
      uses: shogo82148/actions-upload-release-asset@v1
      if: github.event_name == 'push' && github.repository == 'BigBadE/Raven-Language'
      with:
          upload_url: https://uploads.github.com/repos/BigBadE/Raven-Language/releases/123226271/assets
          asset_path: target/release/magpie
          asset_name: Magpie-linux
          overwrite: true
    - name: Release Magpie Wrapper
      uses: shogo82148/actions-upload-release-asset@v1
      if: github.event_name == 'push' && github.repository == 'BigBadE/Raven-Language'
      with:
          upload_url: https://uploads.github.com/repos/BigBadE/Raven-Language/releases/123226271/assets
          asset_path: target/release/magpie-wrapper
          asset_name: Magpie-wrapper-linux
          overwrite: true
    - name: Install DeepSource CLI
      if: github.event_name == 'push' && github.repository == 'BigBadE/Raven-Language'
      run: curl https://deepsource.io/cli | sh
    - name: Merge Coverage report
      if: github.event_name == 'push' && github.repository == 'BigBadE/Raven-Language'
      run: ./llvm/bin/llvm-profdata merge -sparge default_*.profraw -o raven.profdata
    - name: Upload Coverage report
      if: github.event_name == 'push' && github.repository == 'BigBadE/Raven-Language'
      run: ./bin/deepsource report --analyzer test-coverage --key rust --value-file ./raven-profdata