name: Rust

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install LLVM
      uses: robinraju/release-downloader@v1.8
      with: 
        repository: PLC-lang/llvm-package-windows
        tag: "v13.0.0"
        out-file-path: llvm
    - name: Extract 7z
      uses: DuckSoft/extract-7z-action@v1.0
      with:
        pathSource: llvm/LLVM-13.0.0-win64.7z
        pathTarget: llvm
    - name: Set LLVM Env Var
      shell: bash
      run: echo "LLVM_SYS_130_PREFIX=${{github.workspace}}\llvm" >> $GITHUB_ENV
    - name: Add Nightly
      run: rustup toolchain install nightly
    - name: Build
      run: cargo +nightly build --verbose --release --bin magpie
    - name: Build Wrapper
      run: cargo +nightly build --verbose --release --bin magpie-wrapper
    - name: Upload Raven
      uses: actions/upload-artifact@v3.1.3
      with:
        # Artifact name
        name: Magpie-windows.exe # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: target/release/magpie.exe
        # The desired behavior if no files are found using the provided path.
        if-no-files-found: error # optional, default is warn
        # Duration after which artifact will expire in days. 0 means using default retention.
        # Minimum 1 day. Maximum 90 days unless changed from the repository settings page.
        retention-days: 1 # optional
    - name: Upload Magpie Wrapper
      uses: actions/upload-artifact@v3.1.3
      with:
        # Artifact name
        name: Magpie-wrapper-windows.exe # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: target/release/magpie-wrapper.exe
        # The desired behavior if no files are found using the provided path.
        if-no-files-found: error # optional, default is warn
        # Duration after which artifact will expire in days. 0 means using default retention.
        # Minimum 1 day. Maximum 90 days unless changed from the repository settings page.
        retention-days: 1 # optional
    - name: Release Raven
      uses: shogo82148/actions-upload-release-asset@v1
      with:
          upload_url: https://api.github.com/repos/BigBadE/Raven-Language/releases/123226271/
          asset_path: Magpie-windows.exe
          asset_name: Magpie-windows.exe
          overwrite: true
    - name: Release Magpie Wrapper
      uses: shogo82148/actions-upload-release-asset@v1
      with:
          upload_url: https://api.github.com/repos/BigBadE/Raven-Language/releases/123226271/
          asset_path: Magpie-wrapper-windows.exe
          asset_name: Magpie-wrapper-windows.exe
          overwrite: true
